### ISSUE TITLE
SENet 速度跟踪

### ISSUE THREAD

**Issue by rentainhe** [Oneflow-Inc/vision#155]
## 初步使用 nsys 测试 se_resnet50 
* 类脑环境下，测试了se_resnet50  结果如下:
![image](https://user-images.githubusercontent.com/62194666/155304180-fd828322-13c3-4615-bf09-cece97ca38e3.png)

### 15服务器下，使用nsys第一次尝试测试se_resnet50 ，结果如下：

* torch version 总览
![image](https://user-images.githubusercontent.com/62194666/155305019-beac42d4-56bc-4214-9ac5-e8426e04e72b.png)
* oneflow version 总览
![image](https://user-images.githubusercontent.com/62194666/155305141-72916fb2-1fb1-4aa2-b603-bcdb85a07622.png)
总体结构就很不一样。

* torch version 放大视图
![image](https://user-images.githubusercontent.com/62194666/155304745-4093410d-42c3-4878-8f09-11e563de5225.png)
* oneflow version 放大视图
![image](https://user-images.githubusercontent.com/62194666/155305544-bca716bf-f9ce-4bc8-bba7-2d9331a69798.png)
oneflow version 似乎有很多所谓的断流。

* oneflow and torch code
![image](https://user-images.githubusercontent.com/62194666/155306133-17c7579e-9fe7-40b9-afd5-74f55072ae05.png)
代码是从 flowvision.models.se_resnet() 分离出来的，源码见（/vision/flowvision/models/senet.py，senet已经merge)

详见：

profile代码
https://oneflow-test.oss-cn-beijing.aliyuncs.com/senet-nsys/se_resnet50_nsys/senet_of.py
https://oneflow-test.oss-cn-beijing.aliyuncs.com/senet-nsys/se_resnet50_nsys/senet_torch.py

profile链接
https://oneflow-test.oss-cn-beijing.aliyuncs.com/senet-nsys/se_resnet50_nsys/se_resnet50_oneflow_master_sg_wh.qdrep
https://oneflow-test.oss-cn-beijing.aliyuncs.com/senet-nsys/se_resnet50_nsys/se_resnet50_torch_master_sg_wh.qdrep

@BBuf @mls1999725

**Comment by rentainhe** [comment]
@Aries-chen 把模型的速度测试结果贴到这个PR下吧，这边建议是到类脑上进行测试，金山云太慢了

**Comment by Aries-chen** [comment]
> @Aries-chen 把模型的速度测试结果贴到这个PR下吧，这边建议是到类脑上进行测试，金山云太慢了
