### ISSUE TITLE
module 'flowvision.models' has no attribute 'face_recognition'

### ISSUE THREAD

**Issue by PhilippShemetov** [Oneflow-Inc/vision#198]
Hello, I need method for create model iresnet. I saw in documentation that flowvision has model iresnet, but when I import and use `resnest50 = flowvision.models.face_recognition.iresnest50(pretrained=False, progress=True)`, python says `module 'flowvision.models' has no attribute 'face_recognition'`. What can be problem?

**Comment by rentainhe** [comment]
Sorry, we misnamed the interface here, Please use
```python
import flowvision

resnest50 = flowvision.models.face_recognition.iresnet50(pretrained=False, progress=True)
```
to get the right model, we will fix this error later~

**Comment by rentainhe** [comment]
> Hello, I need method for create model iresnet. I saw in documentation that flowvision has model iresnet, but when I import and use `resnest50 = flowvision.models.face_recognition.iresnest50(pretrained=False, progress=True)`, python says `module 'flowvision.models' has no attribute 'face_recognition'`. What can be problem?

It's not `face_recognition.iresnest50` here, it should be `face_recognition.iresnet50`

**Comment by rentainhe** [comment]
`IResNet` model is part of the build plan of `flowvision version 0.2.0`, but we only release the `version 0.1.0` now, if there are still some import error, you can try to use an editable installation of flowvision as follows:
```bash
cd flowvision
pip install -e .
```
Then you can enjoy all the models which are already supported in flowvision.

**Comment by rentainhe** [comment]
Here is the fix PR https://github.com/Oneflow-Inc/vision/pull/199, Thanks very much for helping us to find the problem.
