### ISSUE TITLE
bug: module 'oneflow.nn' has no attribute 'ReLU'

### ISSUE THREAD

**Issue by zhanggj821** [Oneflow-Inc/vision#244]
oneflow/nn/init.py

from oneflow.python.ops.math_ops import fused_scale_tril
from oneflow.python.ops.math_ops import fused_scale_tril_softmax_dropout
**from oneflow.python.ops.math_ops import relu**
from oneflow.python.ops.math_ops import tril

应该是 as ReLU? 难道我的oneflow版本装错了。。
flowvision-0.1.0 oneflow==0.7.0+cu102

**Comment by BBuf** [comment]
![图片](https://user-images.githubusercontent.com/35585791/177076289-a544a968-d702-4c2d-9038-24dbce9c8ac3.png)

可以升级一下oneflow版本

**Comment by zhanggj821** [comment]
0.7.0难道不是最新发行版了吗，你指的升级是指安装nightly版本还是可以直接updata更新

**Comment by BBuf** [comment]
> 0.7.0难道不是最新发行版了吗，你指的升级是指安装nightly版本还是可以直接updata更新

安装nightly版本
